config/routes.rb
Vestibule::Application.routes.draw do

  resources :users, :only => [:show, :edit, :update] do
    member do
      get :selections
    end
  end
  resources :selections, only: [:create]
  resources :proposals, :except => [:destroy] do
    resources :suggestions, :only => [:create, :update]
    member do
      post :withdraw
      post :republish
      post :vote
    end
    collection do
      get :selections
    end
  end

  match "/motivation", :to => "home#motivation", :as => "motivation"
  match "/about", :to => "home#about", :as => "about"
  match "/my-motivation", :to => "home#my_motivation", :as => "complete_motivation"

  match "/dashboard", :to => "dashboard#index"

  match "/auth/:provider/callback", :to => "authentication#callback"
  match "/logout", :to => "authentication#logout", :as => "logout"

  root :to => "home#index"
end

app/models/proposal.rb
require 'statistics2'

class Proposal < ActiveRecord::Base
  belongs_to :proposer, :class_name => 'User'
  has_many :suggestions
  has_many :selections

  has_paper_trail
  acts_as_voteable

  validates :title, :presence => true

  # This allows us to do @proposal.impression_count
  # and other stuff from the 'impressionist' gem.
  is_impressionable counter_cache: { column_name: :impressions_counter_cache }

  scope :without_suggestions_from, lambda { |user|
    if user.suggestions.any?
      where('id NOT IN (?)', user.suggestions.map{ |s| s.proposal_id }.uniq)
    end
  }

  scope :without_votes_from, lambda { |user|
    voted_by_user = user.votes.where(voteable_type: 'Proposal')
    if voted_by_user.any?
      where('id NOT IN (?)', voted_by_user.map{ |s| s.voteable_id }.uniq)
    end
  }

  scope :not_proposed_by, lambda { |user|
    where('proposer_id != ?', user.id)
  }

  scope :active, where(withdrawn: false)
  scope :withdrawn, where(withdrawn: true)

  after_create :update_proposer_score

  class << self
    def update_phase_one_stats!
      transaction do
        all.each { |v| v.update_phase_one_stats! }
      end
    end

    def rank_phase_one!
      transaction do
        self.order('total_wilson_score DESC').each_with_index do |proposal, index|
          proposal.phase_one_ranking = index + 1
          proposal.save!
        end
      end
    end

    def nominate!
      nominated_ids =
          self.active.order(:phase_one_ranking).to_a.
              uniq { |p| p.proposer_id }.
              take(30).
              map { |p| p.id }

      transaction do
        self.update_all('nominated = false')
        self.update_all('nominated = true', ['id IN (?)', nominated_ids])
      end
    end

    def update_phase_two_stats!
      transaction do
        self.where(:nominated => true).includes([{:selections => :user}]).each do |proposal|
          proposal.update_phase_two_stats!
        end
      end
    end

    def rank_phase_two!
      transaction do
        self.where(:nominated => true).order('user_weighted_selections_score DESC').each_with_index do |proposal, index|
          proposal.phase_two_ranking = index + 1
          proposal.save!
        end
      end
    end
  end

  def last_modified
    new_suggestions.any? ? new_suggestions.maximum(:updated_at) : last_modified_by_proposer
  end

  def proposed_by?(user)
    proposer == user
  end

  def new_suggestions
    suggestions.after(last_modified_by_proposer)
  end

  def published?
    !withdrawn
  end

  def withdraw!
    update_attribute(:withdrawn, true)
  end

  def republish!
    update_attribute(:withdrawn, false)
  end

  def update_phase_one_stats!
    self.counted_impressions = unique_impressions_by_unique_users
    self.counted_votes_for = votes_without_bad_users.select { |v| v.vote == true }.size
    self.counted_votes_against = votes_without_bad_users.select { |v| v.vote == false }.size
    self.votes_wilson_score = ci_votes
    self.views_wilson_score = ci_views
    self.total_wilson_score = ci_magic
    self.save!
  end

  PURE_ANALOG_SELECTION_POINTS = {
      1 => 10,
      2 => 9,
      3 => 8,
      4 => 7,
      5 => 6,
      6 => 5,
      7 => 4,
      8 => 3,
      9 => 2,
      10 => 1
  }

  def update_phase_two_stats!
    self.absolute_selections_score =
        selections.inject(0) { |acc, selection| acc + PURE_ANALOG_SELECTION_POINTS[selection.position] }

    self.bad_users_excluded_absolute_selections_score =
        selections_without_bad_users.inject(0) { |acc, selection| acc + PURE_ANALOG_SELECTION_POINTS[selection.position] }

    self.user_weighted_selections_score =
        selections.inject(0) { |acc, selection| acc + (PURE_ANALOG_SELECTION_POINTS[selection.position] * selection.user.contribution_score) }

    self.save!
  end

  #######
  private
  #######

  def last_modified_by_proposer
    [suggestions.by(proposer).maximum(:updated_at), updated_at].compact.max
  end

  def update_proposer_score
    proposer.save
  end

  #### Stats calculations ###

  def ci_magic(confidence = 0.95)
    @ci_magic ||= ((ci_votes(confidence) * 0.8) + (ci_views(confidence) * 0.2))
  end

  def ci_votes(confidence = 0.95)
    @ci_votes ||= begin
      v = self.counted_votes_for
      n = self.counted_votes_for + self.counted_votes_against
      if n == 0
        return 0
      end
      z = Statistics2.pnormaldist(1 - (1 - confidence) / 2)
      phat = 1.0 * v / n
      (phat + z * z / (2 * n) - z * Math.sqrt((phat * (1 - phat) + z * z / (4 * n)) / n)) / (1 + z * z / n)
    end
  end

  def ci_views(confidence = 0.95)
    @ci_views ||= begin
      v = self.counted_impressions
      n = Impression.count('user_id', :distinct => true, :conditions => "user_id IS NOT NULL")
      if n == 0
        return 0
      end
      z = Statistics2.pnormaldist(1 - (1 - confidence) / 2)
      phat = 1.0 * v / n
      (phat + z * z / (2 * n) - z * Math.sqrt((phat * (1 - phat) + z * z / (4 * n)) / n)) / (1 + z * z / n)
    end
  end

  # We ignore users who have voted only on one proposal.
  # This _can_ get smarter...
  def votes_without_bad_users
    @votes_without_bad_users ||= votes.reject { |v| Vote.count(:conditions => {'voter_id' => v.voter_id}) < 2 }
  end

  def unique_impressions_by_unique_users
    @unique_impressions_by_unique_users ||= Impression.count('user_id', :distinct => true, :conditions => "user_id IS NOT NULL AND impressionable_id = #{self.id}")
  end

  def selections_without_bad_users
    @selections_without_bad_users ||= selections.reject { |s| Selection.count(:conditions => {'user_id' => s.user_id}) < 2}
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  impressionist :actions=> [:show]

  respond_to :html
  respond_to :rss, :only => [:index, :show]

  def index
    authorize! :read, Proposal

    @proposals = Proposal.active.order('created_at desc').includes(:suggestions)
    @withdrawn_proposals = Proposal.withdrawn.includes(:suggestions)
    @suggested_proposal = current_user.proposals_without_own_votes.active.sample || Proposal.active.sample if current_user
    @selected_proposals = current_user.selected_proposals if current_user

    if can? :see_nominations, Proposal
      order = current_phase.selection_completed? ? :phase_two_ranking : :phase_one_ranking
      @nominated_proposals = Proposal.active.where(:nominated => true).order(order)
      @leftout_proposals = Proposal.active.where(:nominated => false).order(order)
    end

    respond_with @proposals
  end

  def selections
    authorize! :selections, Proposal
    @proposals = Proposal.where(:nominated => true).order(:phase_two_ranking)
  end

  def show
    @proposal = Proposal.find(params[:id])
    authorize! :read, @proposal

    @previous_proposal = Proposal.active.where("id < ?", @proposal).order("id DESC").first
    @next_proposal = Proposal.active.where("id > ?", @proposal).order("id ASC").first

    @suggestion = Suggestion.new if can?(:create, Suggestion)

    respond_with @proposal
  end

  def new
    @proposal = Proposal.new({:proposer => current_user}.merge(params[:proposal] || {}))
    authorize! :new, @proposal
  end

  def create
    @proposal = Proposal.new({:proposer => current_user}.merge(params[:proposal] || {}))
    authorize! :create, @proposal

    if @proposal.save
      ProposalMailer.new_proposal(@proposal).deliver
      redirect_to proposals_path
    else
      render :new
    end
  end

  def edit
    @proposal = Proposal.find(params[:id])
    authorize! :edit, @proposal
  end

  def update
    @proposal = Proposal.find(params[:id])
    authorize! :update, @proposal

    if @proposal.update_attributes(params[:proposal])
      redirect_to proposal_path(@proposal)
    else
      render :edit
    end
  end

  def withdraw
    @proposal = Proposal.find(params[:id])
    authorize! :withdraw, @proposal

    @proposal.withdraw!
    redirect_to proposal_path(@proposal), alert: "Your proposal has been withdrawn"
  end

  def republish
    @proposal = Proposal.find(params[:id])
    authorize! :republish, @proposal

    @proposal.republish!
    redirect_to proposal_path(@proposal), notice: "Your proposal has been republished"
  end

  def vote
    @proposal = Proposal.find(params[:id])
    authorize! :vote, @proposal

    if params[:vote] == 'clear'
      current_user.unvote_for(@proposal)
      flash[:notice] = 'Your vote has been cleared. Remember to come back to vote again once you are sure!'
    else
      current_user.vote(@proposal, :direction => params[:vote], :exclusive => true )
      flash[:notice] = 'Thank you for casting your vote. Your vote has been captured!'
    end

    redirect_to proposal_path(@proposal)
  end
end

app/views/proposals/_form.html.erb
<%= simple_form_for @proposal do |f| %>
  <% if notification = f.error_notification %>
    <div class="alert alert-error fade in">
      <%= notification %>
    </div>
  <% end %>
  <%= f.input :title %>
  <%= f.input :description, as: :markdown %>
  <%= f.button :submit, "Preview proposal", name: "preview", class: "btn btn-secondary" %>
  <%= f.button :submit, "#{f.object.new_record? ? "Submit" : "Update"} proposal", class: "btn btn-primary" %>
<% end %>

app/views/proposals/_proposal_listing.html.erb
<%
   proposal = proposal_listing
   show_new_suggestions = false unless defined?(show_new_suggestions)
   badge_with_nominations = false unless defined?(badge_with_nominations)
   hide_stats_and_information = false unless defined?(hide_stats_and_information)
%>

<%= content_tag_for :li, proposal do %>
    <% if can?(:see_proposer, Proposal) %>
        <%= link_to proposal, :class => 'title' do %>
            <em><strong><%= proposal.proposer.name %>:</strong></em>
            <%= proposal.title %>
        <% end %>
    <% else %>
        <%= link_to proposal.title, proposal, :class => 'title' %>
    <% end %>
    <% if proposal.confirmed? %><span class="label label-success">confirmed</span><% end %>

    <% if can?(:see_stats, Proposal) && badge_with_nominations %>
        <% if proposal.nominated? %>
            <span class="badge badge-success">Nominated!</span>
        <% else %>
            <span class="badge">Not nominated :(</span>
        <% end %>
    <% end %>

    <br>

    <% unless hide_stats_and_information %>
    <span class="age">
        <% if can?(:see_stats, proposal) %>
            <% if proposal.nominated? && current_phase.selection_completed? %>
                Ranked <em><strong><%= proposal.phase_two_ranking %></strong></em> in Phase 2 with
                a weighted final score of <%= proposal.user_weighted_selections_score.round %>
            <% else %>
                Ranked <em><strong><%= proposal.phase_one_ranking %></strong></em> in Phase 1 with
                <%= proposal.counted_impressions %> unique views,
                <%= proposal.counted_votes_for %> counted upvotes and
                <%= proposal.counted_votes_against %> counted downvotes
            <% end %>
        <% else %>
            <%= proposal_update_information proposal %>
        <% end %>
    </span>
    <% end %>

    <% if show_new_suggestions && proposal.new_suggestions.any? %>
        <%= pluralize proposal.new_suggestions.count, "new suggestion" %>
    <% end %>
<% end %>

app/views/proposals/_suggestions.html.erb
<div id="suggestions">
    <% unless @proposal.suggestions.empty? %>
        <h2>Suggestions</h2>

        <ul class="suggestions">
            <% @proposal.suggestions.latest.each do |suggestion| %>
                <%= content_tag_for(:li, suggestion, :class => suggestion.author == @proposal.proposer ? 'alert alert-block alert-info' : '') do %>
                    <h5 class="author">
                        <% if suggestion.author == @proposal.proposer %>
                            <% if current_user == @proposal.proposer %>
                                You responded
                            <% else %>
                                The proposal author responded
                            <% end %>
                        <% else %>
                            <%= render 'shared/user', :user => suggestion.author %> suggested
                        <% end %>
                        <span class="age"><%= time_ago_in_words suggestion.updated_at %> ago</span>
                        <%= link_to 'edit', '#', class: 'edit_suggestion_link' if can?(:update, suggestion) %>
                    </h5>

                    <section class="body"><%= sanitize(markdown(suggestion.body)) %></section>

                    <% if can?(:update, suggestion) %>
                        <%= simple_form_for [@proposal, suggestion], id: dom_id(suggestion), html: {class: 'hide edit_suggestion_form'} do |f| %>
                            <%= f.input :body,
                                        as: :markdown,
                                        input_html: {rows: 10},
                                        label: false,
                                        hint: "<strong>Be wise when editing a suggestion! The author will be notified automatically." %>
                            <%= f.button :submit, "Update suggestion", class: "btn btn-danger" %>
                        <% end %>
                    <% end %>
                <% end %>
            <% end %>
        </ul>
    <% end %>

    <% if @suggestion && can?(:create, Suggestion) %>
        <div class="add-suggestion">
            <% if current_user == @proposal.proposer %>
                <p class="">You can respond to suggestions here. As the proposer of the talk, your identity will be
                    masked from other visitors.</p>
            <% else %>
                <h2>Improve this proposal</h2>

                <p class="">Help develop this into a good proposal by asking questions about anything that isn't clear,
                    making suggestions about what to include or avoid, and asking for more detail or clarifications.</p>
            <% end %>
        </div>

        <% if @suggestion.body %>
          <h4>Preview of your suggestion:</h4>
          <div class="well">
            <%= markdown @suggestion.body %>
          </div>
        <% end %>

        <%= simple_form_for [@proposal, @suggestion] do |f| %>
            <% if notification = f.error_notification %>
                <div class="alert alert-error fade in">
                    <%= notification %>
                </div>
            <% end %>

            <%= f.input :body, as: :markdown, input_html: {rows: 10} %>
            <%= f.button :submit, "Preview your suggestion", name: "preview", class: "btn btn-secondary" %>
            <%= f.button :submit, "Make your suggestion", class: "btn btn-primary" %>
        <% end %>
    <% end %>
</div>

app/views/proposals/edit.html.erb
<h4>Preview of your proposal:</h4>
<div class="well">
  <h1><%= @proposal.title %></h1>
  <%= markdown @proposal.description %>
</div>

<%= page_title 'Edit your proposal' %>
<%= render "form" %>

app/views/proposals/index.html.erb
<div class="hero-unit">
    <%= page_title "#{Settings.event_name} Call for Presentations" %>

    <% if current_phase.main_text %>
    <p><%= current_phase.main_text.html_safe %></p>
    <% end %>

    <% if current_phase.countdown_text %>
    <p>You have <%= countdown_to_phase_end %> <%= current_phase.countdown_text %></p>
    <% end %>

    <p>
    <% if user_signed_in? %>
        <% if can? :create, Proposal  %>
            <%= link_to "Propose a talk", new_proposal_path, :class => 'btn btn-primary' %>
        <% elsif can?(:create, Selection) %>
            <%= link_to "Define #{Settings.event_name} lineup!", '#nominations', :class => 'btn btn-primary' %>
        <% elsif @suggested_proposal && can?(:vote, @suggested_proposal) %>
            <%= link_to "Cast your votes!", proposal_path(@suggested_proposal), :class => 'btn btn-primary' %>
        <% else %>
            <%= link_to "Follow @#{Settings.twitter_account} on twitter", "http://twitter.com/#{Settings.twitter_account}", :class => 'btn btn-primary', :target => '_blank' %>
        <% end %>
    <% else %>
        <div class="btn-group">
            <%= link_to 'Join the party', '#', :class => 'btn btn-primary dropdown-toggle', :data => {:toggle => 'dropdown'} %>
            <ul class="dropdown-menu">
                <li><span style="padding-left: 10px;">Sign in with...</span></li>
                <li class="divider"></li>
                <%= authentication_links :li %>
            </ul>
        </div>
    <% end %>

    or <%= link_to 'read more about our process', about_path %>.
    </p>
</div>

<% if can?(:see_nominations, Proposal) %>
    <% main_section_class = @nominated_proposals.present? && can?(:create, Selection) ? 'span8' : 'span12' %>

    <% if @nominated_proposals.present? %>
        <section class="row">
            <section id="nominations" class="<%= main_section_class %>">
                <h2>
                    <%= @nominated_proposals.size %> Nominated &amp; active proposals
                </h2>

                <ul class="proposals nominated">
                    <%= render :partial => 'proposal_listing', collection: @nominated_proposals %>
                </ul>
            </section>


            <% if can?(:create, Selection) %>
                <section id="selections" class="span4">
                    <div data-spy="affix" data-offset-top="500" style="top: 0">
                        <h2>
                            Your selections (drag here!)
                            <a data-toggle="tooltip"  data-placement="bottom" title="Just drag your selections from the left and drop them here in order of preference. Easy-peasy!">
                                <i class="icon-question-sign" style="vertical-align: middle"></i>
                            </a>
                        </h2>

                        <div style="margin-bottom: 30px;">
                            <% if current_user.publish_selections? %>
                                <div style="margin-bottom: 15px;">
                                    <%
                                       share_url = selections_user_url(current_user)
                                       share_title = "I've made my selections for the final EuRuKo 2013 lineup! Have you?"
                                    %>
                                    <span class='st_twitter' st_via="euruko" displayText='Tweet' st_url='<%= share_url %>' st_title="<%= share_title %>"></span>
                                    <span class='st_googleplus' displayText='Google+' st_url='<%= share_url %>' st_title="<%= share_title %>"></span>
                                    <span class='st_facebook' displayText='Facebook' st_url='<%= share_url %>' st_title="<%= share_title %>"></span>
                                    <span class='st_sharethis' displayText='ShareThis' st_url='<%= share_url %>' st_title="<%= share_title %>"></span>
                                </div>

                                <div>
                                    <%= form_for current_user do |f| %>
                                        <%= hidden_field_tag :return_to, proposals_path %>
                                        <%= f.hidden_field :publish_selections, :value => 'false' %>
                                        <%= f.submit 'Make my selections private', :class => 'btn btn-mini' %>
                                    <% end %>
                                </div>
                            <% else %>
                                <%= form_for current_user do |f| %>
                                    <%= hidden_field_tag :return_to, proposals_path %>
                                    <%= f.hidden_field :publish_selections, :value => 'true' %>
                                    <%= f.submit 'Share my selection list!', :class => 'btn btn-success btn-small' %>
                                <% end %>
                            <% end %>
                        </div>

                        <ul class="selections">
                            <%= render :partial => 'proposal_listing', collection: @selected_proposals %>
                        </ul>
                    </div>
                </section>
            <% end %>
        </section>
    <% end %>

    <% if @leftout_proposals.present? %>
        <section class="row">
            <section class="<%= main_section_class %>">
                <h2>The following <%= @leftout_proposals.size %> didn't make it into the final list</h2>

                <ul class="proposals">
                    <%= render :partial => 'proposal_listing', collection: @leftout_proposals %>
                </ul>
            </section>
        </section>
    <% end %>
<% else %>
    <section>
        <h2>
            <%= @proposals.size %> Active proposals
            <%= link_to :format => :rss do %>
                <%= image_tag 'feed-icon-14x14.png' %>
            <% end %>
        </h2>

        <ul class="proposals">
            <%= render :partial => 'proposal_listing', collection: @proposals %>
        </ul>
    </section>
<% end %>

<% if @withdrawn_proposals.any? %>
<section>
  <h2>The following <%= @withdrawn_proposals.size %> proposals have been withdrawn:</h2>
  <ul class="proposals">
    <%= render :partial => 'proposal_listing', collection: @withdrawn_proposals %>
  </ul>
</section>
<% end %>

<% content_for :head do %>
  <%= auto_discovery_link_tag :rss, :format => :rss %>
<% end %>

app/views/proposals/new.html.erb
<p class="well">So you want to talk at <%= Settings.event_name %>? That's great! If you haven't already, you may wish to <%= link_to "read about the process", about_path %> to find out how everything works.</p>

<%= page_title 'Propose a talk' %>

<p><strong>NOTE:</strong> proposals are anonymous &mdash; <%= link_to "read more about the process", about_path %>.</p>

<% if @proposal.title %>
  <h4>Preview of your proposal:</h4>
  <div class="well">
    <h1><%= @proposal.title %></h1>
    <%= markdown @proposal.description %>
  </div>
<% end %>

<%= render "form" %>

app/views/proposals/selections.html.erb
<table class="table table-hover sortable final-selections">
    <thead>
    <tr>
        <th>Position</th>
        <th>Phase 1 position</th>
        <th>Author</th>
        <th>Title</th>
        <th style="white-space: nowrap">Abs. score</th>
        <th style="white-space: nowrap">Abs. score <br>(excl. bad users)</th>
        <th style="white-space: nowrap">User weighed score</th>
    </tr>
    </thead>
    <tbody>
    <% @proposals.each_with_index do |proposal, index| %>
    <tr class="<%= index < 10 ? 'success' : 'warning' %>">
        <td><%= index + 1 %></td>
        <td><%= proposal.phase_one_ranking %></td>
        <td><%= link_to proposal.proposer.name, user_path(proposal.proposer) %></td>
        <td><%= link_to proposal.title, proposal_path(proposal) %></td>
        <td><%= proposal.absolute_selections_score %></td>
        <td><%= proposal.bad_users_excluded_absolute_selections_score %></td>
        <td><%= proposal.user_weighted_selections_score %></td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/proposals/show.html.erb
<div id="proposal" class="hero-unit">
    <%= proposal_div(@proposal) do %>
        <%= page_title @proposal.title, no_h1=true %>

        <div class="span4 well pull-right">
            <% if can?(:see_proposer, Proposal) %>
                <%= link_to user_path(@proposal.proposer) do %>
                <em><strong><%= @proposal.proposer.name %></strong></em>
                <br>
                <%= image_tag(avatar_url(@proposal.proposer), :class => "avatar pull-right") %>
                <% end %>
            <% end %>

            <div>
                <% if can? :see_stats, @proposal %>
                    <% if @proposal.nominated? && current_phase.selection_completed? %>
                        Ranked <em><strong><%= @proposal.phase_two_ranking %></strong></em> in Phase 2 with
                        a weighted final score of <%= @proposal.user_weighted_selections_score.round %>
                    <% else %>
                        Ranked <em><strong><%= @proposal.phase_one_ranking %></strong></em> in Phase 1 with
                        <%= @proposal.counted_impressions %> unique views,
                        <%= @proposal.counted_votes_for %> counted upvotes and
                        <%= @proposal.counted_votes_against %> counted downvotes
                    <% end %>
                <% else %>
                    <%= proposal_update_information @proposal %>
                <% end %>
            </div>

            <div style="margin-bottom: 15px;">
                <span class='st_twitter' st_via="euruko" displayText='Tweet'></span>
                <span class='st_googleplus' displayText='Google+'></span>
                <span class='st_facebook' displayText='Facebook'></span>
                <span class='st_sharethis' displayText='ShareThis'></span>
            </div>

            <% if can?(:see_proposer, Proposal) && @proposal.proposer.signup_reason.present? %>
                <div>
                    <h4>About the author</h4>
                    <p><%= sanitize(markdown(@proposal.proposer.signup_reason)) %></p>
                </div>
            <% end %>
        </div>

        <h1>
            <%= @proposal.title %>
        </h1>

        <% if @proposal.confirmed? %><span class="label label-success">Confirmed!</span><% end %>

        <% if @proposal.withdrawn? %>
            <h2 class="withdrawl_explanation">This proposal has been withdrawn...</h2>
        <% end %>
        <div class="description"><%= sanitize(markdown(@proposal.description)) %></div>

        <% if can? :edit, @proposal %>
            <small class="text-info">
                <em>Having second thoughts or a better idea?</em>
            </small>
            &nbsp;

            <%= link_to "Edit proposal", edit_proposal_path(@proposal), class: "btn btn-primary" %>
        <% end %>

        <%= change_proposal_state_button(@proposal) %>

        <% if can? :vote, @proposal %>
            <% if current_user.voted_on?(@proposal) %>
                <br>

                <small class="text-info">
                    <em>You have already voted <strong><%= current_user.voted_for?(@proposal) ? 'up' : 'down' %></strong> this proposal.</em>
                </small>

                <div class="btn-group">
                    <%= link_to 'Changed your mind?', '#', :class => 'btn btn-small dropdown-toggle', :data => {:toggle => 'dropdown'} %>
                    &nbsp;

                    <ul class="dropdown-menu">
                        <li>
                            <%= link_to vote_proposal_path(@proposal, :vote => 'up'), :method => :post do %>
                                <i class="icon-thumbs-up"></i> I would like to see this!
                            <% end %>
                        </li>

                        <li>
                            <%= link_to vote_proposal_path(@proposal, :vote => 'down'), :method => :post do %>
                                <i class="icon-thumbs-down"></i> Not really interested...
                            <% end %>
                        </li>

                        <li class="divider"></li>
                        <li>
                            <%= link_to vote_proposal_path(@proposal, :vote => 'clear'), :method => :post do %>
                                Not sure yet (clear my vote)
                            <% end %>
                        </li>
                    </ul>
                </div>

            <% else %>
                <br>

                <small class="text-info">
                    <em>What do you think about this proposal?</em>
                </small>
                &nbsp;

                <%= link_to vote_proposal_path(@proposal, :vote => 'up'), :method => :post, :class => 'btn btn-success' do %>
                    <i class="icon-thumbs-up icon-white"></i> I would like to see this!
                <% end %>

                <%= link_to vote_proposal_path(@proposal, :vote => 'down'), :method => :post, :class => 'btn btn-inverse' do %>
                    <i class="icon-thumbs-down icon-white"></i> Not really interested...
                <% end %>
            <% end %>

        <% elsif can?(:create, Selection) %>
            <br>

            <small class="text-info">
                <em>Would you like to see this talk during <%= Settings.event_name %>?</em>
            </small>
            &nbsp;

            <%= link_to proposals_path(:anchor => "proposal_#{@proposal.id}"), :class => 'btn btn-primary' do %>
                Drag it to your selection list!
            <% end %>
        <% end %>
    <% end %>
    <br style="clear: both;">
</div>

<div>
    <% if @previous_proposal -%>
        <%= link_to proposal_path(@previous_proposal), class: "btn btn-small", title: @previous_proposal.title, data: {toggle: 'tooltip'} do %>
            <i class="icon-chevron-left"></i>
            Previous
        <% end %>
    <% end %>

    <% if @next_proposal -%>
        <%= link_to proposal_path(@next_proposal), class: "btn btn-small pull-right", title: @next_proposal.title, data: {toggle: 'tooltip'} do %>
            Next
            <i class="icon-chevron-right"></i>
        <% end %>
    <% end %>
</div>
<br>

<%= render partial: 'proposals/suggestions' %>

<% content_for :head do %>
    <%= auto_discovery_link_tag :rss, :format => :rss %>
<% end %>