config/routes.rb
Vestibule::Application.routes.draw do

  resources :users, :only => [:show, :edit, :update] do
    member do
      get :selections
    end
  end
  resources :selections, only: [:create]
  resources :proposals, :except => [:destroy] do
    resources :suggestions, :only => [:create, :update]
    member do
      post :withdraw
      post :republish
      post :vote
    end
    collection do
      get :selections
    end
  end

  match "/motivation", :to => "home#motivation", :as => "motivation"
  match "/about", :to => "home#about", :as => "about"
  match "/my-motivation", :to => "home#my_motivation", :as => "complete_motivation"

  match "/dashboard", :to => "dashboard#index"

  match "/auth/:provider/callback", :to => "authentication#callback"
  match "/logout", :to => "authentication#logout", :as => "logout"

  root :to => "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= render_page_title %></title>

  <!-- Google fonts -->
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,500,700,300italic' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
  <%= yield :head %>
  <% if Settings.google_analytics.enabled %>
  <%= render 'shared/analytics' %>
  <% end %>
</head>
<body class="" data-spy="scroll" data-target="#sidenav">
  <div class="container">
    <div id="nav" class="row">
      <ul class="centered clearfix">
        <li><a class="ir" href="http://euruko2013.org"><%= Settings.event_name %></a></li>
        <% if user_signed_in? -%>
          <li class="dropdown <%= 'active' if active_nav?(dashboard_path, user_path(current_user)) %>">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu sign-in">
                <% if can?(:see, :dashboard) -%><p><%= link_to "Dashboard", dashboard_path, :class => "#{active_nav?(dashboard_path) ? 'active' : ''}" %></p><% end -%>
                <% if can?(:read, Proposal) -%><p><%= link_to "All proposals", proposals_path, :class => "#{active_nav?(proposals_path) ? 'active' : ''}" %></p><% end -%>
                <% if can?(:read, current_user) -%><p><%= link_to "Your profile", user_path(current_user), :class => "#{active_nav?(user_path(current_user)) ? 'active' : ''}" %></p><% end -%>
                <% if can?(:destroy, :session) -%><p><%= link_to "Sign out", logout_path %></p><% end -%>
            </ul>
          </li>
        <% elsif can?(:create, :session) -%>
          <li class="dropdown sign-in">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Sign in
              <b class="caret"></b>
            </a>
            <div class="dropdown-menu">
              <%= authentication_links :p %>
            </div>
          </li>
        <% end -%>

        <li><%= link_to "Blog", 'http://euruko2013.org/blog/' %></li>
        <li><%= link_to "Contact", 'http://euruko2013.org/#contact' %></li>
        <% if can?(:read, Proposal) -%><li <%= active_nav_class(proposals_path) %>><%= link_to "Proposals", proposals_path %></li><% end -%>
        <li><%= link_to "Sponsors", 'http://euruko2013.org/#sponsors' %></li>
        <li><%= link_to "Venue", 'http://euruko2013.org/#venue' %></li>
        <li><%= link_to "Tickets", 'http://euruko2013.org/#tickets' %></li>
        <li><%= link_to "Speakers", 'http://euruko2013.org/#speakers' %></li>
        <li><%= link_to "About", 'http://euruko2013.org/#about' %></li>
       </ul>
    </div>


      <section id="notices" class="row">
          <%= render "shared/notices" %>


          <div class="alert alert-info">
              <i class="icon-bullhorn"></i>&nbsp;&nbsp;
              <strong><em><%= link_to 'See the final speaker lineup!', 'http://euruko2013.org/speakers' %></em></strong>
          </div>

          <% if remind_account_for_signup_reason -%>
              <div class="alert">
                  Other attendees are wondering what you hope to get out of <%= Settings.event_name %>.
                  <%= link_to "Tell them now", edit_user_path(current_user) %>.
              </div>
          <% end -%>

          <% if remind_account_for_author_bio -%>
              <div class="alert">
                  <i class="icon-user"></i>
                  You have some proposals waiting to get into the shortlist!
                  <%= link_to "Why don't you update your profile with some background info about you?", edit_user_path(current_user) %>
              </div>
          <% end -%>
      </section>

    <div id="cfp" class="row">
      <%= yield %>
    </div>
  </div>
  <footer>
      <p><%= link_to "Code of conduct", 'http://euruko2013.org/codeofconduct' %></p>
      <p><%= link_to "About the CfP process", about_path %></p>
      <p><%= link_to "Motivations", motivation_path %></p>
  </footer>
  <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
  <script type="text/javascript">stLight.options({publisher: "a4771cba-dcbc-4ec6-9e9c-4abbf20f04c1", doNotHash: false, doNotCopy: false, hashAddressBar: false, servicePopup:true});</script>
</body>
</html>